JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{66BD1157636971E3}" {
   m_ShopItemAttributes JWK_ShopItemAttributes "{65F547D3690E98F2}" {
    m_iSuppliesPrice 25
   }
  }
  JWK_ItemAttributesConfigRule "{66BD11576371841D}" {
   m_aPrefabs {
    "{B9006AD5B5EDF4C1}Prefabs/Weapons/Magazines/RPD/BC_Drum_762x39_RPD_100rnd_Mixed.et"
    "{5DAA763DEFF104D7}Prefabs/Weapons/Magazines/BC_Drum_762x39_RPD_100rnd_PS.et"
    "{18798C286AA01B86}Prefabs/Weapons/Magazines/BC_Drum_762x39_RPD_100rnd_Tracers.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{65F547D348E301AF}" {
    m_iMoneyPrice 100
    m_iSuppliesPrice 15
   }
  }
  JWK_ItemAttributesConfigRule "{68F152AF23D3D447}" {
   m_sTitle "BAR ammo"
   m_aPrefabs {
    "{56B8E1007A30A1C3}Prefabs/Weapons/Magazines/BAR/BC_Magazine_30-06_BAR_20rnd_M2.et"
    "{34A82AA1E0CBFE4B}Prefabs/Weapons/Magazines/BAR/BC_Magazine_30-06_BAR_20rnd_M2_4Ball_1Tracer.et"
    "{063F3ABA03A63721}Prefabs/Weapons/Magazines/BAR/BC_Magazine_30-06_BAR_20rnd_M2_AP.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{68F152AF23D3D4D9}" {
    m_iMoneyPrice 30
    m_iSuppliesPrice 5
   }
  }
 }
}