JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{669F0143967D2321}" {
   m_ShopItemAttributes JWK_ShopItemAttributes "{65F547D14FEFEF19}" {
    m_iMoneyPrice 175
    m_iSuppliesPrice 10
   }
  }
  JWK_ItemAttributesConfigRule "{669F014397B60CE3}" {
   m_aPrefabs {
    "{2A9A50C23773AC87}Prefabs/Weapons/Magazines/Carl Gustaf M45/BC_Magazine_9x19_M45_36rnd_Ball.et"
    "{0B17FB1F4A9F5289}Prefabs/Weapons/Magazines/M3A1/BC_Magazine_45acp_M3A1_30rnd_Ball.et"
    "{EA76BE12E7C97CF1}Prefabs/Weapons/Magazines/MP40/BC_Magazine_9x19_MP40_32rnd_Ball.et"
    "{5587A9FD1C78FE17}Prefabs/Weapons/Magazines/PPSH41/BC_Magazine_Ppsh41_35rnd_Stick.et"
    "{1D5D4BC1F0777C9B}Prefabs/Weapons/Magazines/Thompson/BC_Magazine_M1928A1_45acp_Thompson_30rnd_Stick.et"
    "{5C43D5083942A22B}Prefabs/Weapons/Magazines/Thompson/BC_Magazine_M1A1_45acp_Thompson_30rnd_Stick.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{65F547D195D1ED9E}" {
    m_iSuppliesPrice 4
   }
  }
  JWK_ItemAttributesConfigRule "{669F014397FE708E}" {
   m_bEnabled 0
  }
  JWK_ItemAttributesConfigRule "{68F152A0898813A9}" {
   m_sTitle "SMGs ammo big"
   m_aPrefabs {
    "{4198718E0E2A3A83}Prefabs/Weapons/Magazines/PPSH41/BC_Magazine_71rd_PPSH41.et"
    "{AFA22BD030DDBC13}Prefabs/Weapons/Magazines/Thompson/BC_Magazine_M1928A1_45acp_Thompson_50rnd_Drum.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{68F152A089881037}" {
    m_iMoneyPrice 40
    m_iSuppliesPrice 12
   }
  }
  JWK_ItemAttributesConfigRule "{68FD55C0549D5DB2}" {
   m_sTitle "Bayonets"
   m_aPrefabs {
    "{76E4B06195684DCF}Prefabs/Weapons/Attachments/Bayonets/Bayonet_M45/BC_Bayonet_M45.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{68FD55C3912994B1}" {
    m_iMoneyPrice 10
    m_iSuppliesPrice 1
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{669F014381E3646E}" {
   m_aTargetFactionRoles {
   }
   m_aAddItems {
   }
  }
 }
}