JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{66BD1157073816A8}" {
   m_ShopItemAttributes JWK_ShopItemAttributes "{65F547D39592BD9B}" {
    m_iSuppliesPrice 35
   }
  }
  JWK_ItemAttributesConfigRule "{66BD115707002EEC}" {
   m_ShopItemAttributes JWK_ShopItemAttributes "{65F547D392C387CF}" {
    m_iMoneyPrice 250
    m_iSuppliesPrice 15
   }
  }
  JWK_ItemAttributesConfigRule "{68F152AFBB235D81}" {
   m_sTitle "40mm ammo"
   m_aPrefabs {
    "{0DE4A55F189A32CB}Prefabs/Weapons/Ammo/BC_Ammo_Grenade_M576_Buckshot.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{68F152AFA5019AE7}" {
    m_iMoneyPrice 15
    m_iSuppliesPrice 3
   }
  }
  JWK_ItemAttributesConfigRule "{68F152AFD3F5CD25}" {
   m_sTitle "M67 ammo"
   m_aPrefabs {
    "{4D44C563104F77BB}Prefabs/Weapons/Ammo/BC_Ammo_Rocket_M37A1.et"
    "{5971423B21CB6C16}Prefabs/Weapons/Ammo/BC_Ammo_Rocket_M590E1_Flechette_50_250.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{68F152AFD3F5CD84}" {
    m_iMoneyPrice 250
    m_iSuppliesPrice 25
   }
  }
 }
}