JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{65FD42EC15458CBD}" {
   m_aPrefabs {
    "{3D3758C525994D3A}Prefabs/Weapons/Shotguns/Double Barrel/BC_Shotgun_Double_Barrel_610mm.et"
    "{3C4FB3D9D54B46DF}Prefabs/Weapons/Shotguns/Double Barrel/BC_Shotgun_Double_Barrel_760mm.et"
    "{E7A3BA1F06C057FF}Prefabs/Weapons/Shotguns/Double Barrel/BC_Shotgun_Double_Barrel_Sawn_Off.et"
    "{9E8405BDD24BCF69}Prefabs/Weapons/Shotguns/Ithaca 37/BC_Shotgun_Ithaca_37_V2.et"
    "{563C338A655857B7}Prefabs/Weapons/Shotguns/Remington 870/BC_Shotgun_Remington_870_V2.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{65FD42F9C172E2A9}" {
    m_iSuppliesPrice 6
   }
  }
  JWK_ItemAttributesConfigRule "{65FD42EC1A874597}" {
   m_ShopItemAttributes JWK_ShopItemAttributes "{65F547D1CBD5F709}" {
    m_iMoneyPrice 1
   }
  }
  JWK_ItemAttributesConfigRule "{68FD55C3A581D0AA}" {
   m_sTitle "Bayonets"
   m_aPrefabs {
    "{5E6EE617A4C5469D}Prefabs/Weapons/Attachments/Bayonets/BC_Bayonet_M1917.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{68FD55C3912994B1}" {
    m_iMoneyPrice 10
    m_iSuppliesPrice 1
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{65FD42ECDD6152B1}" {
   m_aTargetFactionRoles {
   }
   m_aAddItems {
   }
  }
 }
}