JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{67113E2951043D4C}" {
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E2951043D45}" {
    m_iMoneyPrice 150
    m_iSuppliesPrice 8
   }
  }
  JWK_ItemAttributesConfigRule "{67113E29AF7CC847}" {
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E29AF7CC8FA}" {
    m_iMoneyPrice 450
    m_iSuppliesPrice 25
   }
  }
  JWK_ItemAttributesConfigRule "{67113E2984ED4EB5}" {
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E2984ED4950}" {
    m_iSuppliesPrice 10
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{67113E2951043D7B}" {
   m_aTargetFactionRoles {
   }
   m_aAddItems {
   }
  }
 }
}